version: 0.2

phases:
  build:
    commands:
      - echo "Limpiando artifacts locales..."
      - rm -f chichicux.zip function.zip response.json event.json lambda_actual.zip

      - echo "Listando repo..."
      - ls -lah

      - echo "Listando carpeta function..."
      - ls -lah function

      - echo "Empaquetando desde function/ con app.py en root..."
      - cd function
      - zip -r ../chichicux.zip .
      - cd ..

      - echo "Contenido del zip:"
      - unzip -l chichicux.zip

      - echo "Verificando que NO exista function.zip dentro..."
      - if unzip -l chichicux.zip | grep -q "function.zip"; then echo "ERROR: function.zip esta dentro del zip"; exit 1; fi

      - echo "Verificando que SI exista app.py en root..."
      - if ! unzip -l chichicux.zip | grep -q " app.py"; then echo "ERROR: app.py no esta en el zip"; exit 1; fi

      - echo "Deploy a Lambda..."
      - aws lambda update-function-code --function-name suma-cicd --zip-file fileb://chichicux.zip
