AWSTemplateFormatVersion: '2010-09-09'
Description: Pipeline sanity check

Resources:
  TestLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/pipeline/sanity
      RetentionInDays: 7
