AWSTemplateFormatVersion: '2010-09-09'
Description: Pipeline test OK

Resources:
  TestLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/test/pipeline
      RetentionInDays: 7
